# -*- coding: utf-8 -*-
"""Gini Tree

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1enhCJK2LRyrHxt1IUSPKjCjie5lZWzNO
"""

from google.colab import files
import pandas as pd
uploaded = files.upload()

import io
df = pd.read_csv(io.BytesIO(uploaded['oof.csv']))

import sklearn.datasets as datasets
import pandas as pd
from PIL import Image
x =  df.values[:,0:4]
y=df.values[:,4]
print(df)
from sklearn.tree import DecisionTreeClassifier
dtree=DecisionTreeClassifier(criterion = "gini")
dtree.fit(x,y)
from sklearn.externals.six import StringIO  
from IPython.display import Image  
from sklearn.tree import export_graphviz
import pydotplus
dot_data = StringIO()
export_graphviz(dtree, out_file=dot_data,  
                filled=True, rounded=True,
                special_characters=True)
graph = pydotplus.graph_from_dot_data(dot_data.getvalue())  
Image(graph.create_png())